<a href="https://colab.research.google.com/github/aruphar/Linked-List/blob/master/PytorchPractice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
# Reshaping if we don't know the number of items
# using -1
my_torch2 = torch.arange(10)
print(f"my_torch2 : \n{my_torch2}")

my_torch2 = my_torch2.reshape(5,-1)
print(f"\nAfter reshaping with (5,-1)\n{my_torch2}")

my_torch2 = my_torch2.reshape(-1,5)
print(f"\nAfter reshaping with (-1,5)\n{my_torch2}")

my_torch2 : 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

After reshaping with (5,-1)
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

After reshaping with (-1,5)
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [16]:
# Using View
my_torch3 = torch.arange(10)
print(f"my_torch3 = \n{my_torch3}")

my_torch3 = my_torch3.view(2,5)
print(f"\nAfter using view = \n{my_torch3}")

my_torch3 = 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

After using view = 
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
